filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /mnt/logs/*.log
  fields:
    log_type: application
  processors:
    - add_host_metadata: ~
    - add_cloud_metadata: ~

output.logstash:
  hosts: ["logstash:5000"]
  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
